#define SEM_MUTEX "/mutex"
#define SEM_MUTEX_INIT_VALUE 1

#define STORAGE_SPACE 12

#define SEM_SPACE_TOTAL "/space_total"
#define SEM_SPACE_TOTAL_INIT_VALUE STORAGE_SPACE

#define PART_A_PER_TIME_PRODUCE 2
#define PART_A_REQUIRED 4

#define PART_B_PER_TIME_PRODUCE 1
#define PART_B_REQUIRED 3

#define STORAGE_SPACE_A ( STORAGE_SPACE - PART_B_REQUIRED )
#define STORAGE_SPACE_B ( STORAGE_SPACE - PART_A_REQUIRED )

#define SEM_SPACE_A "/space_A"
#define SEM_SPACE_A_INIT_VALUE STORAGE_SPACE_A

#define SEM_SPACE_B "/space_B"
#define SEM_SPACE_B_INIT_VALUE STORAGE_SPACE_B

#define SEM_STORAGE_A "/storage_A"
#define SEM_STORAGE_A_INIT_VALUE 0

#define SEM_STORAGE_B "/storage_B"
#define SEM_STORAGE_B_INIT_VALUE 0
